### ISSUE TITLE
Can't verify license request signature; either the platform is wrong or the key has changed!

### ISSUE THREAD

**Issue by yuusakuri** [cryptonek/widevine-l3-decryptor#3]
The following message is displayed on the console.
```
Can't verify license request signature; either the platform is wrong or the key has changed!
```

Only a few days ago I was able to get the key.
The browser is Chromium installed from Chocolatey. The OS is Windows 10 2004.

**Comment by devporter007** [comment]
Already solved 
https://github.com/cryptonek/widevine-l3-decryptor/issues/2

**Comment by yuusakuri** [comment]
solved. I would like you to add this solution to an easy-to-understand place such as the README.
